# Generated by Django 3.2 on 2022-05-09 09:26

from django.db import migrations

import account.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_add_custom_user_model'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
    ]
