# Generated by Django 4.0.4 on 2022-05-17 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_add_company_and_sector_models'),
        ('account', '0001_add_custom_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=150, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_or_mobile',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone/Mobile number'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='user',
            name='related_company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users_queryset',
                to='company.company',
                verbose_name='Company',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name='Email address',
            ),
        ),
    ]
