# Generated by Django 4.0.4 on 2022-06-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_add_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                (
                    'related_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                        related_name='notification_settings',
                    ),
                ),
                (
                    'company_registration',
                    models.BooleanField(
                        default=True,
                        help_text='Receive notifications to review a newly registered company account',
                        verbose_name='Company registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification setting',
                'verbose_name_plural': 'Notification settings',
            },
        ),
    ]
