# Generated by Django 4.0.4 on 2022-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailchangerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='has_email_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                verbose_name='Active',
                default=True,
                help_text=(
                    'Designates whether a user account is active or not.'
                    '<br> Use this flag to deactivate/block a user account'
                ),
            ),
        ),
    ]
