[tool.black]
skip-string-normalization = 1
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
known_django = "django"
sections = ["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
src_paths = 'apps'
