{{- if .Values.ingress.enabled -}}
{{- $secretName := "" -}}
{{- if .Values.ingress.useLetsEncrypt -}}
{{- $secretName = include "epr-tool.fullname" . }}
{{- else if .Values.ingress.secretName -}}
{{- $secretName = .Values.ingress.secretName -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "epr-tool.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-frontend
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingress.useLetsEncrypt }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
{{- if .Values.ingress.secretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host.frontend | quote }}
      secretName: {{ $secretName }}-frontend
{{- end }}
  rules:
    - host: {{ .Values.ingress.host.frontend | quote }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "epr-tool.fullname" . }}-frontend
                port:
                  number: 3000
{{- end }}
