{{- if .Values.ingress.enabled -}}
{{- $secretName := "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "epr-tool.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-backend
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host.backend | quote }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "epr-tool.fullname" . }}-backend
                port:
                  number: 8000
{{- end }}
