{{- if .Values.initjob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "epr-tool.fullname" . }}-init-job
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-init-job
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "epr-tool.fullname" . }}-init-job
      labels:
        app.kubernetes.io/name: {{ include "epr-tool.name" . }}-init-job
        helm.sh/chart: {{ include "epr-tool.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      {{ if $.Values.backend.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.backend.serviceAccount.serviceAccountName }}
      {{ end }}
      restartPolicy: OnFailure
      containers:
      - name: init-job
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command: {{ .Values.initjob.command }}
        args: {{ .Values.initjob.commandArgs }}
        envFrom:
          - configMapRef:
              name: {{ include "epr-tool.fullname" . }}-backend
              optional: false
          - secretRef:
              name: {{ include "epr-tool.fullname" . }}-backend
              optional: false
        resources:
        {{- toYaml .Values.initjob.resources | nindent 12 }}
        volumeMounts:
          - name: backend
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: backend
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "epr-tool.fullname" . }}-backend
      imagePullSecrets:
        - name: ai-registry
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
