apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "epr-tool.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-frontend
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "epr-tool.name" . }}-frontend
