apiVersion: v1
kind: Secret
metadata:
  name: {{ include "epr-tool.fullname" . }}-django-secret
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-django-secret
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.backend.django.secretKey | b64enc | quote }}
{{- if .Values.backend.db.enabled }}
  DATABASE_PASSWORD: {{ .Values.backend.db.password | b64enc | quote }}
{{- end }}
{{- if .Values.backend.aws.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.aws.secretAccessKey | b64enc | quote }}
{{- end }}
