# Generated by Django 4.0.4 on 2022-07-26 09:13

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'ul', 'ol'])),
                    (
                        'fullWidthImage',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'image',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('alt_text', wagtail.blocks.CharBlock()),
                                            ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                        ]
                                    ),
                                ),
                                ('header', wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'ul', 'ol'])),
                    (
                        'fullWidthImage',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'image',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('alt_text', wagtail.blocks.CharBlock()),
                                            ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                        ]
                                    ),
                                ),
                                ('header', wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
