# Generated by Django 4.0.4 on 2022-05-17 11:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import company.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Name')),
                (
                    'related_sector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subsectors_queryset',
                        to='company.sector',
                        verbose_name='Sector',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Subsector',
                'verbose_name_plural': 'Subsectors',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator],
                        verbose_name='Email address',
                    ),
                ),
                (
                    'registration_number',
                    models.CharField(max_length=20, unique=True, verbose_name='Registration Number'),
                ),
                (
                    'street_and_house_number',
                    models.CharField(
                        max_length=255,
                        validators=[company.validators.validate_street_contains_number],
                        verbose_name='Street and House Number',
                    ),
                ),
                (
                    'zip_code',
                    models.CharField(
                        max_length=255, validators=[company.validators.validate_zip_code], verbose_name='Postal Code'
                    ),
                ),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('province', models.CharField(max_length=255, verbose_name='Province')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                (
                    'additional_address_info',
                    models.CharField(blank=True, max_length=255, verbose_name='Additional Adress Information'),
                ),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone number')),
                ('mobile', models.CharField(blank=True, max_length=16, verbose_name='Mobile numer')),
                ('fax', models.CharField(blank=True, max_length=16, verbose_name='Fax number')),
                (
                    'related_sector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='companies_queryset',
                        to='company.sector',
                        verbose_name='Sector',
                    ),
                ),
                (
                    'related_subsector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='companies_queryset',
                        to='company.subsector',
                        verbose_name='Subsector',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
