# Generated by Django 4.0.4 on 2022-06-01 06:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_add_company_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_created',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created by',
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='lastmodified_at',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='lastmodified_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_lastmodified',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Last modified by',
            ),
        ),
    ]
