# Generated by Django 4.0.4 on 2022-05-17 16:07

from django.core.management import call_command
from django.db import migrations, models


def migrate_existing_sectors(apps, schema_editor):
    # to correctly initialize the default translation field
    call_command('update_translation_fields')


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_add_company_related_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subsector',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subsector',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.RunPython(migrate_existing_sectors, migrations.RunPython.noop),
    ]
