# Generated by Django 4.0.4 on 2022-05-19 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_subsector_related_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesSubsectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='related_sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='related_subsector',
        ),
        migrations.AddField(
            model_name='company',
            name='related_subsector',
            field=models.ManyToManyField(
                related_name='companies_queryset',
                through='company.CompaniesSubsectors',
                to='company.subsector',
                verbose_name='Subsector',
            ),
        ),
        migrations.AddField(
            model_name='companiessubsectors',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'
            ),
        ),
        migrations.AddField(
            model_name='companiessubsectors',
            name='subsector',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='company.subsector', verbose_name='Subsector'
            ),
        ),
    ]
