# Generated by Django 4.0.4 on 2022-08-04 09:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_company_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInvoiceRecipient',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                (
                    'lastmodified_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
                    ),
                ),
                (
                    'related_company',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='related_additional_invoice_recipient',
                        serialize=False,
                        to='company.company',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.')], max_length=20, verbose_name='Title'
                    ),
                ),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name='Email address',
                    ),
                ),
                ('phone_or_mobile', models.CharField(blank=True, max_length=16, verbose_name='Phone/Mobile number')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'lastmodified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_lastmodified',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Additional invoice recipient',
                'verbose_name_plural': 'Additional invoice recipients',
            },
        ),
    ]
