# Generated by Django 4.0.4 on 2022-08-31 09:46

from django.db import migrations, models

import company.validators


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_unique_company_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='identification_number',
            field=models.CharField(
                blank=True,
                help_text='National identification number',
                max_length=255,
                null=True,
                unique=True,
                validators=[company.validators.validate_string_without_whitespaces],
                verbose_name='VAT / tax number',
            ),
        ),
    ]
