# Generated by Django 4.0.4 on 2022-06-08 10:43

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import common.validators
import packaging_report.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                (
                    'lastmodified_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'lastmodified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_lastmodified',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Forecast Submission',
                'verbose_name_plural': 'Forecast Submissions',
            },
        ),
        migrations.CreateModel(
            name='PackagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                (
                    'lastmodified_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
                    ),
                ),
                (
                    'timeframe',
                    models.PositiveIntegerField(
                        choices=[(1, '1 month'), (3, '3 months'), (12, '12 months')], verbose_name='Timeframe'
                    ),
                ),
                (
                    'year',
                    models.PositiveIntegerField(verbose_name='Year'),
                ),
                (
                    'start_month',
                    models.PositiveIntegerField(
                        choices=[
                            (1, 'January'),
                            (2, 'February'),
                            (3, 'March'),
                            (4, 'April'),
                            (5, 'May'),
                            (6, 'June'),
                            (7, 'July'),
                            (8, 'August'),
                            (9, 'September'),
                            (10, 'October'),
                            (11, 'November'),
                            (12, 'December'),
                        ],
                        validators=[packaging_report.models.validate_report_month],
                        verbose_name='Start Month',
                    ),
                ),
                (
                    'timezone_info',
                    models.CharField(
                        max_length=32,
                        validators=[packaging_report.models.validate_report_timezone],
                        verbose_name='Timezone info',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'lastmodified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_lastmodified',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Packaging Report',
                'verbose_name_plural': 'Packaging Reports',
            },
        ),
        migrations.CreateModel(
            name='MaterialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                (
                    'lastmodified_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
                    ),
                ),
                (
                    'quantity',
                    models.FloatField(
                        validators=[common.validators.validate_greater_than_zero], verbose_name='Quantity (Kg)'
                    ),
                ),
                (
                    'monthly_quantities',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(verbose_name='Quantity per month'),
                        default=list,
                        size=12,
                        verbose_name='Monthly Quantities',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'lastmodified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_lastmodified',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
                (
                    'related_packaging_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='material_records_queryset',
                        to='packaging.packaginggroup',
                        verbose_name='Packaging Group',
                    ),
                ),
                (
                    'related_packaging_material',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='material_records_queryset',
                        to='packaging.material',
                        verbose_name='Material',
                    ),
                ),
                (
                    'related_submission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='material_records_queryset',
                        to='packaging_report.forecastsubmission',
                        verbose_name='Submission',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Material record',
                'verbose_name_plural': 'Material records',
            },
        ),
        migrations.AddField(
            model_name='forecastsubmission',
            name='related_report',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='related_forecast',
                to='packaging_report.packagingreport',
                verbose_name='Packaging Report',
            ),
        ),
        migrations.AddConstraint(
            model_name='materialrecord',
            constraint=models.UniqueConstraint(
                fields=('related_packaging_group', 'related_packaging_material', 'related_submission'),
                name='unique_material_record_in_report_submission',
            ),
        ),
    ]
