# Generated by Django 4.0.4 on 2022-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_report', '0002_packagingreport_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrecord',
            name='monthly_quantities',
        ),
    ]
