# Generated by Django 4.0.4 on 2022-06-22 10:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packaging_report', '0003_remove_monthly_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialrecord',
            name='unique_material_record_in_report_submission',
        ),
        migrations.RenameField(
            model_name='materialrecord',
            old_name='related_submission',
            new_name='related_forecast_submission',
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='related_forecast_submission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_records_queryset',
                to='packaging_report.forecastsubmission',
                verbose_name='Forecast Submission',
            ),
        ),
        migrations.CreateModel(
            name='FinalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
                ),
                (
                    'lastmodified_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'lastmodified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_lastmodified',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
                (
                    'related_report',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='related_final_submission',
                        to='packaging_report.packagingreport',
                        verbose_name='Packaging Report',
                    ),
                ),
                (
                    'fees',
                    models.FloatField(default=0.0, help_text='Report actual quantities fees', verbose_name='Fees'),
                ),
            ],
            options={
                'verbose_name': 'Final Submission',
                'verbose_name_plural': 'Final Submissions',
            },
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='related_final_submission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_records_queryset',
                to='packaging_report.finalsubmission',
                verbose_name='Final Submission',
            ),
        ),
        migrations.AddConstraint(
            model_name='materialrecord',
            constraint=models.UniqueConstraint(
                fields=(
                    'related_packaging_group',
                    'related_packaging_material',
                    'related_forecast_submission',
                    'related_final_submission',
                ),
                name='unique_material_record_in_report_submission',
            ),
        ),
    ]
