# Generated by Django 4.0.4 on 2022-06-30 08:06

from django.db import migrations, models

import apps.common.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_report', '0004_add_final_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingreport',
            name='invoice_file',
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=apps.common.storage_backend.private_file_storage,
                upload_to='invoices',
                verbose_name='Invoice File',
            ),
        ),
    ]
