# Generated by Django 4.0.4 on 2022-07-18 14:16

from django.db import migrations, models

import apps.packaging_report.models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_report', '0005_add_report_invoice_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingreport',
            name='start_month',
            field=models.PositiveIntegerField(
                choices=[
                    (1, 'January'),
                    (2, 'February'),
                    (3, 'March'),
                    (4, 'April'),
                    (5, 'May'),
                    (6, 'June'),
                    (7, 'July'),
                    (8, 'August'),
                    (9, 'September'),
                    (10, 'October'),
                    (11, 'November'),
                    (12, 'December'),
                ],
                db_index=True,
                validators=[apps.packaging_report.models.validate_report_month],
                verbose_name='Start Month',
            ),
        ),
        migrations.AlterField(
            model_name='packagingreport',
            name='year',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Year'),
        ),
    ]
