# Generated by Django 4.0.4 on 2022-07-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_registration_number'),
        ('packaging_report', '0006_add_index_to_year_and_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingreport',
            name='related_company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='packaging_report_queryset',
                to='company.company',
                verbose_name='Company',
            ),
        ),
    ]
