# Generated by Django 4.0.4 on 2022-08-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_report', '0007_alter_packagingreport_related_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalsubmission',
            options={'verbose_name': 'Final Report', 'verbose_name_plural': 'Final Reports'},
        ),
        migrations.AlterModelOptions(
            name='forecastsubmission',
            options={'verbose_name': 'Forecast Report', 'verbose_name_plural': 'Forecast Reports'},
        ),
        migrations.AlterModelOptions(
            name='materialrecord',
            options={'verbose_name': 'Report Packaging entry', 'verbose_name_plural': 'Report Packaging entries'},
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='related_final_submission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_records_queryset',
                to='packaging_report.finalsubmission',
                verbose_name='Final Report',
            ),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='related_forecast_submission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_records_queryset',
                to='packaging_report.forecastsubmission',
                verbose_name='Forecast Report',
            ),
        ),
    ]
