apiVersion: v1
kind: Service
metadata:
  name: {{ include "epr-tool.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-backend
    helm.sh/chart: {{ include "epr-tool.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "epr-tool.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
